package stl

import (
	"bufio"
	"encoding/binary"
	"fmt"
	"io"
	"os"
)

// binaryTriSize is the on-disk size of one binary STL triangle: a normal and
// three vertices as float32, plus a 2-byte attribute field.
const binaryTriSize = 50

// headerText deliberately avoids the leading token "solid" so that parsers
// which sniff the first five bytes do not misread our output as ASCII.
const headerText = "Binary STL generated by stl-wizard"

// Write emits m as a binary STL. Output is always binary; ASCII is read-only.
func Write(w io.Writer, m *Mesh) error {
	bw := bufio.NewWriter(w)

	var header [80]byte
	copy(header[:], headerText)
	if _, err := bw.Write(header[:]); err != nil {
		return err
	}
	if err := binary.Write(bw, binary.LittleEndian, uint32(len(m.Tris))); err != nil {
		return err
	}

	buf := make([]byte, binaryTriSize)
	for _, t := range m.Tris {
		n := t.Normal()
		vals := [12]float64{
			n[0], n[1], n[2],
			t.A[0], t.A[1], t.A[2],
			t.B[0], t.B[1], t.B[2],
			t.C[0], t.C[1], t.C[2],
		}
		for i, v := range vals {
			binary.LittleEndian.PutUint32(buf[i*4:], float32bits(v))
		}
		buf[48], buf[49] = 0, 0
		if _, err := bw.Write(buf); err != nil {
			return err
		}
	}
	return bw.Flush()
}

func WriteFile(path string, m *Mesh) error {
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create %s: %w", path, err)
	}
	if err := Write(f, m); err != nil {
		f.Close()
		return fmt.Errorf("write %s: %w", path, err)
	}
	return f.Close()
}
