// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Cut(arg1:string,arg2:main.PlaneInput):Promise<main.CutOutcome>;

export function ExportAll():Promise<main.ExportOutcome>;

export function OpenModel():Promise<main.TreeView>;

export function Select(arg1:string):Promise<main.TreeView>;

export function Undo():Promise<main.TreeView>;
