// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoSplit(arg1, arg2) {
  return window['go']['main']['App']['AutoSplit'](arg1, arg2);
}

export function Cut(arg1, arg2, arg3) {
  return window['go']['main']['App']['Cut'](arg1, arg2, arg3);
}

export function ExportAll() {
  return window['go']['main']['App']['ExportAll']();
}

export function OpenModel(arg1) {
  return window['go']['main']['App']['OpenModel'](arg1);
}

export function OpenPath(arg1, arg2) {
  return window['go']['main']['App']['OpenPath'](arg1, arg2);
}

export function Select(arg1) {
  return window['go']['main']['App']['Select'](arg1);
}

export function Undo() {
  return window['go']['main']['App']['Undo']();
}
