// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPlane(arg1, arg2) {
  return window['go']['main']['App']['AddPlane'](arg1, arg2);
}

export function AutoSplit(arg1, arg2) {
  return window['go']['main']['App']['AutoSplit'](arg1, arg2);
}

export function ClearPlan() {
  return window['go']['main']['App']['ClearPlan']();
}

export function Cut(arg1, arg2, arg3) {
  return window['go']['main']['App']['Cut'](arg1, arg2, arg3);
}

export function DeletePlane(arg1) {
  return window['go']['main']['App']['DeletePlane'](arg1);
}

export function ExecutePlan() {
  return window['go']['main']['App']['ExecutePlan']();
}

export function ExportAll() {
  return window['go']['main']['App']['ExportAll']();
}

export function ExportPlates(arg1) {
  return window['go']['main']['App']['ExportPlates'](arg1);
}

export function ExportPlatesTo(arg1, arg2) {
  return window['go']['main']['App']['ExportPlatesTo'](arg1, arg2);
}

export function OpenModel(arg1) {
  return window['go']['main']['App']['OpenModel'](arg1);
}

export function OpenPath(arg1, arg2) {
  return window['go']['main']['App']['OpenPath'](arg1, arg2);
}

export function Plan() {
  return window['go']['main']['App']['Plan']();
}

export function PlanFitToPrinter(arg1) {
  return window['go']['main']['App']['PlanFitToPrinter'](arg1);
}

export function RenamePlane(arg1, arg2) {
  return window['go']['main']['App']['RenamePlane'](arg1, arg2);
}

export function ReorderPlan(arg1) {
  return window['go']['main']['App']['ReorderPlan'](arg1);
}

export function Select(arg1) {
  return window['go']['main']['App']['Select'](arg1);
}

export function SeparateBodies(arg1) {
  return window['go']['main']['App']['SeparateBodies'](arg1);
}

export function SetPlaneEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetPlaneEnabled'](arg1, arg2);
}

export function Undo() {
  return window['go']['main']['App']['Undo']();
}

export function UpdatePlane(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePlane'](arg1, arg2, arg3);
}
