// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {cut} from '../models';

export function AddPlane(arg1:main.PlaneInput,arg2:cut.PinSpec):Promise<main.PlanView>;

export function AutoSplit(arg1:cut.Bed,arg2:cut.PinSpec):Promise<main.AutoSplitOutcome>;

export function ClearPlan():Promise<main.PlanView>;

export function Cut(arg1:string,arg2:main.PlaneInput,arg3:cut.PinSpec):Promise<main.CutOutcome>;

export function DeletePlane(arg1:string):Promise<main.PlanView>;

export function ExecutePlan():Promise<main.ExecuteOutcome>;

export function ExportAll():Promise<main.ExportOutcome>;

export function ExportPlates(arg1:cut.Bed):Promise<main.PlateOutcome>;

export function ExportPlatesTo(arg1:string,arg2:cut.Bed):Promise<main.PlateOutcome>;

export function OpenModel(arg1:boolean):Promise<main.TreeView>;

export function OpenPath(arg1:string,arg2:boolean):Promise<main.TreeView>;

export function Plan():Promise<main.PlanView>;

export function PlanFitToPrinter(arg1:cut.Bed):Promise<main.PlanView>;

export function RenamePlane(arg1:string,arg2:string):Promise<main.PlanView>;

export function Select(arg1:string):Promise<main.TreeView>;

export function SeparateBodies(arg1:string):Promise<main.SeparateOutcome>;

export function SetPlaneEnabled(arg1:string,arg2:boolean):Promise<main.PlanView>;

export function Undo():Promise<main.TreeView>;

export function UpdatePlane(arg1:string,arg2:main.PlaneInput,arg3:cut.PinSpec):Promise<main.PlanView>;
