// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cut} from '../models';
import {main} from '../models';

export function AutoSplit(arg1:cut.Bed,arg2:cut.PinSpec):Promise<main.AutoSplitOutcome>;

export function Cut(arg1:string,arg2:main.PlaneInput,arg3:cut.PinSpec):Promise<main.CutOutcome>;

export function ExportAll():Promise<main.ExportOutcome>;

export function ExportPlates(arg1:cut.Bed):Promise<main.PlateOutcome>;

export function ExportPlatesTo(arg1:string,arg2:cut.Bed):Promise<main.PlateOutcome>;

export function OpenModel(arg1:boolean):Promise<main.TreeView>;

export function OpenPath(arg1:string,arg2:boolean):Promise<main.TreeView>;

export function Select(arg1:string):Promise<main.TreeView>;

export function SeparateBodies(arg1:string):Promise<main.SeparateOutcome>;

export function Undo():Promise<main.TreeView>;
