// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cut(arg1, arg2) {
  return window['go']['main']['App']['Cut'](arg1, arg2);
}

export function OpenModel() {
  return window['go']['main']['App']['OpenModel']();
}
